apiVersion: apps/v1
kind: Deployment
metadata:
  name: gateway-deploy
  labels:
    name: gateway-deploy
    app: microservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
      type: microservice
  template:
    metadata:
      name: gateway-pod
      labels:
        app: gateway
        type: microservice
    spec:
      containers:
        - name: gateway-app
          image: aoi182/serviciosapigateway:latest
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 80
