apiVersion: v1
kind: Pod
metadata:
  name: microservice-libreria-pod
  labels:
    name: microservice-libreria-pod
    type: microservice
spec:
  containers:
    - name: microservice-libreria
      image: aoi182/serviciosapilibreria:latest
      resources:
        limits:
          memory: "128Mi"
          cpu: "500m"
      ports:
        - containerPort: 80
      env:
        - name: MongoDb__ConnectionString
          value: mongodb://admin:Admin123.@mongo-service:27017
