apiVersion: v1
kind: Service
metadata:
  name: microservice-gateway-service
spec:
  type: LoadBalancer
  selector:
    name: microservice-gateway-pod
    type: microservice
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30010