apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-deploy
spec:
  selector:
    matchLabels:
      name: mongo-pod
      type: database
  template:
    metadata:
      name: mongo-pod
      labels:
        name: mongo-pod
        type: database
    spec:
      containers:
      - name: mongo-pod
        image: mongo:latest
        command:
          - /bin/bash
          - -c
        env:
          - name: MONGO_INITDB_ROOT_USERNAME
            value: "admin"
          - name: MONGO_INITDB_ROOT_PASSWORD
            value: "Admin123."
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 27017